EasyMove/urls.py
from django.urls import path
from . import views
app_name = 'EasyMove'
urlpatterns = [
    #item list view
    path('', views.home, name='easy-move-home'),
    path('item-list', views.easy_move_list, name = 'easy-move-list'),
    path('items/<int:item_id>', views.easy_move_items_detail, name="item-detail"),
    path('items/add-item', views.easy_move_add_item, name="add-item"),
    path('items/edit-item/<int:item_id>', views.easy_move_edit_item, name="edit-item"),
    path('items/edit-item/submit-edit/<int:item_id>',views.easy_move_submit_edit,name="submit-edit"),
    path('items/delete-item/<int:item_id>', views.easy_move_delete_item, name="delete-item"),
    path('change-location', views.easy_move_change_location, name="change-location"),
    path('items/<int:item_id>/compare', views.easy_move_item_compare, name="compare-item"),
    path('items/add-comment', views.new_comment_add,name="add-comment"),
    path('delete-comment', views.delete_comment, name="delete-comment"),
    path('edit-comment', views.edit_comment, name="edit-comment"),
    path('items/change-role', views.update_user_role, name="change-role"),
    path('search', views.item_search, name="item-search"),
]

cs5774DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('EasyMove/', include('EasyMove.urls', namespace='EasyMove')),
    path('users/', include('users.urls', namespace='users')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    #item list view
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name="profile"),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('edit-profile/<str:username>', views.edit_profile, name='edit-profile'),
    path('submit-profile-edit/<str:username>', views.submit_profile_edit, name='submit-profile-edit'),
    path('change-password', views.change_password, name='change-password'),
]

EasyMove/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class EasyMoveItem(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    location = models.CharField(max_length=200)
    availability = models.CharField(max_length=200)
    condition = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    item_img = models.ImageField(upload_to='', blank=False)
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('EasyMove:item-detail', args=[self.id])

class UserInfo(models.Model):
    ROLE = (
        ('R', 'Regular_user'),
        ('A', 'Admin'),
    )
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=10)
    role = models.CharField(max_length=1, choices=ROLE)



class Comment(models.Model):
    author = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    commentTitle = models.CharField(max_length=200)
    commentText = models.TextField(blank=False)
    date_posted = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey(EasyMoveItem, on_delete=models.CASCADE)

EasyMove/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import EasyMoveItem, UserInfo, Comment, User
from actions.models import Action
from django.http import JsonResponse
from django.contrib.contenttypes.models import ContentType
import requests
import json


# Create your views here.

# Home view
def home(request):
    items = EasyMoveItem.objects.all().order_by('-date_posted')
    if request.session.get("username", False):
        user = User.objects.get(username=request.session.get("username"))

        # filter the feeds that are related to the current user
        user_upload = EasyMoveItem.objects.all().filter(user_id=user.id)
        actions_user = Action.objects.all().filter(user_id=user.id)
        actions_target_user = Action.objects.all().filter(target_id=user.id,target_ct=ContentType.objects.get_for_model(User))
        action_target_item = Action.objects.all().filter(target_id__in=user_upload,target_ct=ContentType.objects.get_for_model(EasyMoveItem))

        actions = actions_user|actions_target_user|action_target_item
        actions = actions.order_by("-date_created")[:5]

        return render(request,
                      "EasyMove/home.html",
                      {"items": items, "actions":actions}
                      )
    else:
        return render(request,
                      "EasyMove/home.html",
                      {"items": items}
                      )

# List view
def easy_move_list(request):
    items = EasyMoveItem.objects.all().order_by('-date_posted')
    actions = Action.objects.all()
    return render(request,
              "EasyMove/easy_move/list.html",
              {"items": items, "actions":actions}
              )

# Item deatils view
def easy_move_items_detail(request, item_id):
    item = EasyMoveItem.objects.get(id=item_id)
    comments = Comment.objects.filter(item_id=item_id).order_by('-date_posted')
    return render(request,
                  "EasyMove/easy_move/detail.html",
                  {"item": item, "comments": comments},
                  )


# Sell/add new item view
def easy_move_add_item(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('EasyMove:easy-move-home')

    if request.method == 'POST':
        # process the form
        title = request.POST.get("add-title")
        price = request.POST.get("add-price")
        condition = request.POST.get("add-condition")
        description = request.POST.get("description")
        availability = request.POST.getlist("add-availability")
        location = request.POST.get("add-location")
        item_img = request.FILES["item_image"]

        # check the from content.
        # check if the content are only space.
        if title.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The title is invalid/empty, please try again.")
            return redirect("EasyMove:add-item")

        if condition.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The condition is invalid/empty, please try again.")
            return redirect("EasyMove:add-item")

        if description.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The description is invalid/empty, please try again.")
            return redirect("EasyMove:add-item")

        if location.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The location is invalid/empty, please try again.")
            return redirect("EasyMove:add-item")

        # get the value of checkbox and re-construct them
        option = '/'.join(availability)
        if option == '':
            messages.add_message(request, messages.ERROR,
                                 "Please select at least one availability option.")
            return redirect("EasyMove:add-item")

        # Detect the content of image using Microsoft Azure Computer Vision AI Service
        endpoint = "https://easymovevision.cognitiveservices.azure.com/vision/v3.1/analyze"
        parameters = {
            'visualFeatures':'Adult'
        }
        headers = {
            'Content-Type': 'application/octet-stream',
            'Ocp-Apim-Subscription-Key': '4d013d6596ad47f3af39739e0699742b',
        }
        response = requests.post(endpoint,headers=headers, params=parameters,data=item_img)
        result = response.json()

        # Handle API error message.
        if response.status_code != 200 and response.status_code != 201:
            messages.add_message(request, messages.ERROR,
                                 "%s" % result["message"])
            return redirect("EasyMove:add-item")

        # warn user with corresponding error
        if result['adult']['isAdultContent']:
            messages.add_message(request, messages.ERROR,
                                 "Your image contains adult content,please change it.")
            return redirect("EasyMove:add-item")

        if result['adult']['isRacyContent']:
            messages.add_message(request, messages.ERROR,
                                 "Your image contains racy content,please change it.")
            return redirect("EasyMove:add-item")

        if result['adult']['isGoryContent']:
            messages.add_message(request, messages.ERROR,
                                 "Your image contains gory content,please change it.")
            return redirect("EasyMove:add-item")

        user = User.objects.get(username=request.session.get("username"))

        new_item = EasyMoveItem(
            title=title,
            price = price,
            condition = condition,
            description = description,
            availability = option,
            location = location,
            author=request.session.get('username'),
            user=user,
            item_img = item_img
        )
        new_item.save()


        action=Action(
            user=user,
            verb="created the new item",
            target=new_item
        )
        action.save()

        messages.add_message(request, messages.SUCCESS, "You successfully submitted the new item: %s" %new_item.title )

        return redirect("EasyMove:item-detail", new_item.id)

    else:
        # show the form
        # messages.add_message(request, messages.WARNING, "Failed add the item, try add again")
        return render(request,
                      "EasyMove/easy_move/add.html",
                      )


def easy_move_edit_item(request, item_id):
    editing_item = EasyMoveItem.objects.get(id=item_id)

    return render(request,
                  "EasyMove/easy_move/edit.html",
                  {"item": editing_item}
                  )


# Edit item view
def easy_move_submit_edit(request, item_id):

    if not request.session.get("username", False):
        return redirect('EasyMove:easy-move-home')

    editing_item = EasyMoveItem.objects.get(id=item_id)

    if request.method == 'POST':
        # process the form

        title = request.POST.get("add-title")
        price = request.POST.get("add-price")
        condition = request.POST.get("add-condition")
        description = request.POST.get("description")
        availability = request.POST.getlist("add-availability")
        location = request.POST.get("add-location")

        # Check if the submit content are valid.
        if title.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The title is invalid/empty, please try again.")
            return redirect("EasyMove:edit-item", item_id)

        if condition.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The condition is invalid/empty, please try again.")
            return redirect("EasyMove:edit-item", item_id)

        if description.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The description is invalid/empty, please try again.")
            return redirect("EasyMove:edit-item", item_id)

        if location.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The location is invalid/empty, please try again.")
            return redirect("EasyMove:edit-item", item_id)

        option = '/'.join(availability)
        if option == '':
            messages.add_message(request, messages.ERROR,
                                 "Please select at least one availability option.")
            return redirect("EasyMove:edit-item", item_id)

        # update information
        editing_item.title = title
        editing_item.price = price
        editing_item.condition = condition
        editing_item.description = description
        editing_item.availability = option
        editing_item.location = location

        # save update
        editing_item.save()

        user = User.objects.get(username=request.session.get("username"))
        # log the action
        action = Action(
            user=user,
            verb="edited the item",
            target=editing_item
        )
        action.save()

        messages.add_message(request, messages.INFO, "You successfully edited the item %s" %editing_item.title)

        return redirect("EasyMove:item-detail", item_id)
    else:
        # messages.add_message(request, messages.WARNING, "Failed edit the item %s" %editing_item.title)
        return redirect("EasyMove:item-detail", item_id)



def easy_move_delete_item(request, item_id):
    # check if user logged in
    if not request.session.get("username", False):
        return redirect('EasyMove:easy-move-home')

    title = EasyMoveItem.objects.get(pk=item_id).title

    EasyMoveItem.objects.get(pk=item_id).delete()

templates/EasyMove/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<meta name="description" content="The homepage for EasyMove">
	<title>EasyMove{% block page-title %}{% endblock %}</title>

	<script src="{% static "js/jquery-3.5.1.min.js" %}"></script>
	<script src="{% static "js/script.js" %}"></script>
	<link rel="stylesheet" href="{% static "css/responsive-header.css" %}">
	<link rel="stylesheet" href="{% static "css/responsive-footer.css" %}">
	<link rel="stylesheet" href="{% static "css/main.css" %}">

    {% block css-file %}
    {% endblock %}
    {# blocks for add css files for other html pages#}


</head>

{# The base file include the header and footer for each page. #}

<body>
	<main>
		<!-- Home page header; all the HTML pages have the same header -->
		<header>
			<!-- Left header include logo and logotext, which could link to home page -->
			<div id="leftHeader">
				<div id="logo">
					<a href="{% url "EasyMove:easy-move-home" %}">
					<img src="{% static "img/site/logo.png" %}" alt="EasyMove logo"/></a>
				</div>
				<a href="{% url "EasyMove:easy-move-home" %}">
				<div id="logoText">
					<h1>EasyMove</h1>
					<h4>Find all you need here</h4>
				</div>
				</a>
			</div>

			<!-- Mid-header include search box and navigation bar -->
			<div id="midHeader">
					<form id="searchForm" action="{% url "EasyMove:item-search" %}" method="GET">
						<input type="text" id="searchBar" name="search" placeholder="Jellycat">
						<input type="image" name="submit" src="{% static "img/site/search-icon.png" %}">
					</form>
			</div>

			<!-- Right header include link to userprofile and message interface -->
			<div id="rightHeader">

                {% if request.session.username %}
                {# only logged-in user could access the burger menu#}
				<div class="menuIcon">
					<img src="{% static "img/site/menu-icon.png" %}" alt="burger menu icon" /></a>
				</div>

				<nav class="menu" style="display: none">
					<a href="{% url "EasyMove:easy-move-home" %}" class="menuItem">Home</a>
					<a href="{% url "EasyMove:easy-move-list" %}" class="menuItem">Item List</a>
					<a href="{% url "users:profile" request.session.username %}" class="menuItem">Profile</a>
					<a href="{% url "EasyMove:add-item" %}" class="menuItem">Sell</a>
                    <a href="{% url "users:logout" %}" class="menuItem">Log Out</a>
				</nav>
                {% endif %}

                {% if request.session.username %}
                {# if user logged in, then present the username here #}
                <div id="userInfo">
					<a href="{% url "users:profile" request.session.username %}" class="greet">Hi, {{ request.session.username }}</a>
				</div>

                {% else %}
                {# otherwise, shows the log in option here #}
                <form id="login" action="{% url "users:login" %}" method="POST">
                    {% csrf_token %}
                    <div class="input">
                        <input type="text" name="username" placeholder="Username">
					    <input type="password" name="pw" placeholder="Password">
                    </div>

                    <div>
                        <input type="submit" name="submit" value="login"> | <a href="{% url 'users:register' %}" ><u>Register</u></a>
                    </div>
				</form>

                {% endif %}
			</div>
		</header>


        {#  Block for main content of each page #}
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
            {% endif %}
		<section>

            {% block content %}{% endblock %}

        </section>

		<footer>
			<div id="leftFooter">
				<p>@ 2020 Made by Nan</p>
			</div>

			<div id="midFooter">
				<a href="#">Contacts</a> |
				<a href="#">Directions</a> |
				<a href="#">Privacy</a>
			</div>

			<div id="rightFooter">
				<img src="{% static "img/site/facebook-icon.png" %}" alt="facebook icon" />
				<img src="{% static "img/site/twitter-icon.png" %}" alt="twitter icon" />
			</div>

		</footer>

	</main>
</body>
</html>

templates/EasyMove/home.html
{% extends "EasyMove/base.html" %}
{% load static %}
}


{% block css-file %}
    <link rel="stylesheet" href="{% static "css/responsive-home.css" %}">
{% endblock %}


{% block content %}

{% if request.session.username %}

     <div id="welcomePage">
	     <div id="welcome">
	        <h1>Welcome to EasyMove!</h1>
	        <h2>Start your study abroad life here.</h2>
	     </div>


        {# For logged-in user, their location should be memorized #}
	    <div id="findLocation">
	 	    <img src="{% static  "img/site/location-mark.png" %}" alt="location mark" style="height: 30px" />
	 	    <p>{{ request.session.location}}</p>
	 	    <button id="changeLocation" data-ajax-url="{% url "EasyMove:change-location" %}">Change Location</button>
	    </div>

        <hr class="divider">

        <div class="recent-activity">
            {% include "actions/action/feed.html" %}
        </div>

{% else %}

     <div id="welcomePage">
	     <div id="welcome">
	         <h1>Welcome to EasyMove!</h1>
	         <h2>Start your study abroad life here.</h2>
	     </div>

        <div id="findLocation">
	    	<img src="{% static  "img/site/location-mark.png" %}" alt="location mark" style="height: 30px" />

            {#  User who didn't log in should select their own location #}
	    	<p>Find your location here</p>
	    	<form>
	    		<input type="text" name="location">
	    		<input type="submit" name="submit" value="Go Find!">
	    	</form>
	    </div>

{% endif %}
    </div>

<div id="itemList">
    {% if request.session.username %}
    {# Only logged-in users are able to use the filter function #}
    <div id="sortTools">
	    <div id="deliverOptions">
	    	<input type="checkbox" id="checkDeliver" name="deliver" checked>
	    	<label for="checkDeliver">Deliver</label>
	    	<input type="checkbox" id="checkPickup" name="pickup" checked>
	    	<label for="checkPickup">Pickup</label>
	    	<input type="checkbox" id="checkMail" name="mail" checked>
	    	<label for="checkMail">Mail</label>
	    </div>
	    <div id="sort">
	    	<select name="sortBy" id="sortBy">
	    		<option value="newest">Newest</option>
	    		<option value="priceH">Price:H</option>
	    		<option value="priceL">Price:L</option>
	    	</select>
		</div>
	</div>
    {% endif %}

    <div id="items">
        {% if items|length == 0 %}
            <h2>Sorry, there are no items right now.</h2>
        {% else %}
            {% for item in items %}
                {# iterate items and present in this page #}
                <a href="{% url "EasyMove:item-detail" item.id %}" class="itemBox" data-created-date="{{ item.date_posted }}">
    	            <img src="{{ item.item_img.url }}" alt="{{ item.title }}" />

    	            <p class="price" data-item-price="{{ item.price }}">${{ item.price }}</p>

    	            <p class="itemName">{{ item.title}}</p>
    	            <p class="location">{{ item.location}}</p>
    	    	    <p class="availability">{{ item.availability}}</p>
    	        </a>
            {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock %}