EasyMove/urls.py
from django.urls import path
from . import views
app_name = 'EasyMove'
urlpatterns = [
    #item list view
    path('', views.home, name='easy-move-home'),
    path('item-list', views.easy_move_list, name = 'easy-move-list'),
    path('items/<int:item_id>', views.easy_move_items_detail, name="item-detail"),
    path('items/add-item', views.easy_move_add_item, name="add-item"),
    path('items/edit-item/<int:item_id>', views.easy_move_edit_item, name="edit-item"),
    path('items/edit-item/submit-edit/<int:item_id>',views.easy_move_submit_edit,name="submit-edit"),
    path('items/delete-item/<int:item_id>', views.easy_move_delete_item, name="delete-item"),
    path('change-location', views.easy_move_change_location, name="change-location"),
    path('items/<int:item_id>/compare', views.easy_move_item_compare, name="compare-item"),
    path('items/add-comment', views.new_comment_add,name="add-comment"),
    path('delete-comment', views.delete_comment, name="delete-comment"),
    path('edit-comment', views.edit_comment, name="edit-comment"),
    path('items/change-role', views.update_user_role, name="change-role"),
    path('search', views.item_search, name="item-search"),
]

cs5774DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('EasyMove/', include('EasyMove.urls', namespace='EasyMove')),
    path('users/', include('users.urls', namespace='users')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    #item list view
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name="profile"),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('edit-profile/<str:username>', views.edit_profile, name='edit-profile'),
    path('submit-profile-edit/<str:username>', views.submit_profile_edit, name='submit-profile-edit'),
    path('change-password', views.change_password, name='change-password'),
]

EasyMove/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class EasyMoveItem(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    location = models.CharField(max_length=200)
    availability = models.CharField(max_length=200)
    condition = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    item_img = models.ImageField(upload_to='', blank=False)
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('EasyMove:item-detail', args=[self.id])

class UserInfo(models.Model):
    ROLE = (
        ('R', 'Regular_user'),
        ('A', 'Admin'),
    )
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=10)
    role = models.CharField(max_length=1, choices=ROLE)



class Comment(models.Model):
    author = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    commentTitle = models.CharField(max_length=200)
    commentText = models.TextField(blank=False)
    date_posted = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey(EasyMoveItem, on_delete=models.CASCADE)

EasyMove/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import EasyMoveItem, UserInfo, Comment, User
from actions.models import Action
from django.http import JsonResponse
from django.contrib.contenttypes.models import ContentType
import requests
import json


# Create your views here.

# Home view
def home(request):
    items = EasyMoveItem.objects.all().order_by('-date_posted')
    if request.session.get("username", False):
        user = User.objects.get(username=request.session.get("username"))

        # filter the feeds that are related to the current user
        user_upload = EasyMoveItem.objects.all().filter(user_id=user.id)
        actions_user = Action.objects.all().filter(user_id=user.id)
        actions_target_user = Action.objects.all().filter(target_id=user.id,target_ct=ContentType.objects.get_for_model(User))
        action_target_item = Action.objects.all().filter(target_id__in=user_upload,target_ct=ContentType.objects.get_for_model(EasyMoveItem))

        actions = actions_user|actions_target_user|action_target_item
        actions = actions.order_by("-date_created")[:5]

        return render(request,
                      "EasyMove/home.html",
                      {"items": items, "actions":actions}
                      )
    else:
        return render(request,
                      "EasyMove/home.html",
                      {"items": items}
                      )

# List view
def easy_move_list(request):
    items = EasyMoveItem.objects.all().order_by('-date_posted')
    actions = Action.objects.all()
    return render(request,
              "EasyMove/easy_move/list.html",
              {"items": items, "actions":actions}
              )

# Item deatils view
def easy_move_items_detail(request, item_id):
    item = EasyMoveItem.objects.get(id=item_id)
    comments = Comment.objects.filter(item_id=item_id).order_by('-date_posted')
    return render(request,
                  "EasyMove/easy_move/detail.html",
                  {"item": item, "comments": comments},
                  )


# Sell/add new item view
def easy_move_add_item(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('EasyMove:easy-move-home')

    if request.method == 'POST':
        # process the form
        title = request.POST.get("add-title")
        price = request.POST.get("add-price")
        condition = request.POST.get("add-condition")
        description = request.POST.get("description")
        availability = request.POST.getlist("add-availability")
        location = request.POST.get("add-location")
        item_img = request.FILES["item_image"]

        # check the from content.
        # check if the content are only space.
        if title.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The title is invalid/empty, please try again.")
            return redirect("EasyMove:add-item")

        if condition.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The condition is invalid/empty, please try again.")
            return redirect("EasyMove:add-item")

        if description.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The description is invalid/empty, please try again.")
            return redirect("EasyMove:add-item")

        if location.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The location is invalid/empty, please try again.")
            return redirect("EasyMove:add-item")

        # get the value of checkbox and re-construct them
        option = '/'.join(availability)
        if option == '':
            messages.add_message(request, messages.ERROR,
                                 "Please select at least one availability option.")
            return redirect("EasyMove:add-item")

        # Detect the content of image using Microsoft Azure Computer Vision AI Service
        endpoint = "https://easymovevision.cognitiveservices.azure.com/vision/v3.1/analyze"
        parameters = {
            'visualFeatures':'Adult'
        }
        headers = {
            'Content-Type': 'application/octet-stream',
            'Ocp-Apim-Subscription-Key': '4d013d6596ad47f3af39739e0699742b',
        }
        response = requests.post(endpoint,headers=headers, params=parameters,data=item_img)
        result = response.json()

        # Handle API error message.
        if response.status_code != 200 and response.status_code != 201:
            messages.add_message(request, messages.ERROR,
                                 "%s" % result["message"])
            return redirect("EasyMove:add-item")

        # warn user with corresponding error
        if result['adult']['isAdultContent']:
            messages.add_message(request, messages.ERROR,
                                 "Your image contains adult content,please change it.")
            return redirect("EasyMove:add-item")

        if result['adult']['isRacyContent']:
            messages.add_message(request, messages.ERROR,
                                 "Your image contains racy content,please change it.")
            return redirect("EasyMove:add-item")

        if result['adult']['isGoryContent']:
            messages.add_message(request, messages.ERROR,
                                 "Your image contains gory content,please change it.")
            return redirect("EasyMove:add-item")

        user = User.objects.get(username=request.session.get("username"))

        new_item = EasyMoveItem(
            title=title,
            price = price,
            condition = condition,
            description = description,
            availability = option,
            location = location,
            author=request.session.get('username'),
            user=user,
            item_img = item_img
        )
        new_item.save()


        action=Action(
            user=user,
            verb="created the new item",
            target=new_item
        )
        action.save()

        messages.add_message(request, messages.SUCCESS, "You successfully submitted the new item: %s" %new_item.title )

        return redirect("EasyMove:item-detail", new_item.id)

    else:
        # show the form
        # messages.add_message(request, messages.WARNING, "Failed add the item, try add again")
        return render(request,
                      "EasyMove/easy_move/add.html",
                      )


def easy_move_edit_item(request, item_id):
    editing_item = EasyMoveItem.objects.get(id=item_id)

    return render(request,
                  "EasyMove/easy_move/edit.html",
                  {"item": editing_item}
                  )


# Edit item view
def easy_move_submit_edit(request, item_id):

    if not request.session.get("username", False):
        return redirect('EasyMove:easy-move-home')

    editing_item = EasyMoveItem.objects.get(id=item_id)

    if request.method == 'POST':
        # process the form

        title = request.POST.get("add-title")
        price = request.POST.get("add-price")
        condition = request.POST.get("add-condition")
        description = request.POST.get("description")
        availability = request.POST.getlist("add-availability")
        location = request.POST.get("add-location")

        # Check if the submit content are valid.
        if title.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The title is invalid/empty, please try again.")
            return redirect("EasyMove:edit-item", item_id)

        if condition.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The condition is invalid/empty, please try again.")
            return redirect("EasyMove:edit-item", item_id)

        if description.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The description is invalid/empty, please try again.")
            return redirect("EasyMove:edit-item", item_id)

        if location.strip() == '':
            messages.add_message(request, messages.ERROR,
                                 "The location is invalid/empty, please try again.")
            return redirect("EasyMove:edit-item", item_id)

        option = '/'.join(availability)
        if option == '':
            messages.add_message(request, messages.ERROR,
                                 "Please select at least one availability option.")
            return redirect("EasyMove:edit-item", item_id)

        # update information
        editing_item.title = title
        editing_item.price = price
        editing_item.condition = condition
        editing_item.description = description
        editing_item.availability = option
        editing_item.location = location

        # save update
        editing_item.save()

        user = User.objects.get(username=request.session.get("username"))
        # log the action
        action = Action(
            user=user,
            verb="edited the item",
            target=editing_item
        )
        action.save()

        messages.add_message(request, messages.INFO, "You successfully edited the item %s" %editing_item.title)

        return redirect("EasyMove:item-detail", item_id)
    else:
        # messages.add_message(request, messages.WARNING, "Failed edit the item %s" %editing_item.title)
        return redirect("EasyMove:item-detail", item_id)



def easy_move_delete_item(request, item_id):
    # check if user logged in
    if not request.session.get("username", False):
        return redirect('EasyMove:easy-move-home')

    title = EasyMoveItem.objects.get(pk=item_id).title

    EasyMoveItem.objects.get(pk=item_id).delete()

templates/EasyMove/easy_move/add.html
{% extends "EasyMove/base.html" %}
{% load static %}


{% block css-file %}
    <link rel="stylesheet" href="{% static "css/responsive-upload.css" %}">
{% endblock %}


{% block content %}


<div id="addDetail">

	{# This page will be directed to the list page after submitting the new item #}
	<form id="addItem" action="{% url "EasyMove:add-item" %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div>
            <label>Upload item's image</label>
            <input type="file" name="item_image" id="item_image" required>
        </div>

		<div>
			<label for="add-title">Title*</label>
			<input type="text" id="add-title" name="add-title" required/>
		</div>

		<div>
			<label for="add-price">Price*</label>
			<input type="number" id="add-price" name="add-price" min="0" required/>
		</div>

		<div>
			<label for="add-condition">Condition*</label>
			<input type="text" id="add-condition" name="add-condition" required/>
		</div>

		<div>
			<label for="description">Description*</label>
            <textarea id="description" name="description" required></textarea>
		</div>

		<div>
            <label for="add-availability">Shipping Availability*</label>
	    	<input type="checkbox" id="checkDeliver" value="Deliver" name="add-availability">
	    	<label for="checkDeliver">Deliver</label>
	    	<input type="checkbox" id="checkPickup" value="Pickup" name="add-availability">
	    	<label for="checkPickup">Pickup</label>
	    	<input type="checkbox" id="checkMail" value="Mail" name="add-availability">
	    	<label for="checkMail">Mail</label>

		</div>

		<div>
			<label for="add-location">Location*</label>
			<input type="text" id="add-location" name="add-location" required/>
		</div>


		<div id="operation">
			<input type="submit" name="submit" />
		</div>

	</form>
</div>

{% endblock %}

templates/EasyMove/easy_move/detail.html
{% extends "EasyMove/base.html" %}
{%  load static %}
{% load humanize %}

{% block css-file %}
    <link rel="stylesheet" href="{% static "css/responsive-item.css" %}">
{% endblock %}

{# This tempate is for item details #}
{% block content %}
        <div id="itemDetail">
            <div id="itemImageSet">
				<img src="{{ item.item_img.url}}" alt="image of {{item.title}}" />
			</div>


			<div id="itemInfo">
				<div id="info">
					<p class="price">Price: ${{ item.price }}</p>
					<p class="name">{{ item.title}}</p>
					<p class="location">{{ item.location }}</p>
                    <p class="postedBy">Posted by: <a href="{% url "users:profile" item.user.username %}">{{ item.user.username }}</a></p>
					<p class="avilability">Avilability: {{ item.availability}}</p>
					<p class="postTime">Posted {{item.date_posted |naturaltime}}</p>
				</div>
				<hr/>
				<div id="condition">
					<h3>Condition: {{ item.condition}}</h3>
					<p>{{ item.description }}</p>
{#                    <p>Key Phrases: {{ key_phrases }} </p>#}
				</div>
				<hr/>

                {% if request.session.username %}
				<div id="operationButtons">
					<button id="compare" data-item-title="{{ item.title }}" data-ajax-url="{% url "EasyMove:compare-item" item.id%}" data-out-url="{% url "EasyMove:item-detail" item.id %}">Compare</button>

                    {% if request.session.role == "Admin" or request.session.username == item.author %}
                        <button onclick="location.href = '{% url "EasyMove:edit-item" item.id %}' ">Edit</button>
                        <button onclick="location.href = '{% url "EasyMove:delete-item" item.id %}'">Delete</button>
                    {% endif %}
				</div>
                {% endif %}

            <div id="compareResult" >
                <div class="similar_item_link">
                </div>
            </div>


			</div>

        </div>



        <div id="itemComment">

        <hr/>
            <h2>Comments</h2>
            <div id="all-comments" data-edit-url="{% url "EasyMove:edit-comment" %}" data-delete-url="{% url "EasyMove:delete-comment" %}">
                {% if comments|length == 0 %}
                    <p class="no-comment">No comments yet.</p>
                {% else %}
                    {% for comment in comments %}
                        <div class="comment-block">
                            <hr/>
                            <p class="title">{{ comment.commentTitle }}</p>
                            <p class="commentText">{{ comment.commentText}}</p>
                            <p class="post-time">Posted {{ comment.date_posted|naturaltime }} by <a href="{{  comment.user.details.get_absolute_url }}"> {{ comment.author }}</a> </p>
                            {% if request.session.role == "Admin" or request.session.username == comment.author %}
                                <button class="edit-comment">Edit Comment</button>
                                <button class="submit-edit-comment" data-comment-id="{{ comment.id }}" data-ajax-url="{% url "EasyMove:edit-comment" %}" style="display: none" >Submit Edit</button>
                                <button class="delete-comment" data-comment-id="{{ comment.id }}" data-ajax-url="{% url "EasyMove:delete-comment" %}">Delete Comment</button>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <hr/>

            {% if request.session.username %}
            <div id="addComment">
                <h2>Add Comment</h2>

                    <div class="commentArea">
                        <label for="commentTitle">Add Title *</label><br/>
                        <input type="text" id="commentTitle" name="commentTitle" required>
                    </div>

                    <div class="commentArea">
                        <label for="comment">Add Your Comment *</label><br/>
                        <textarea id="comment" name="comment" required></textarea>
                    </div>

                    <div class="commentArea">
                        <button id="submitComment" data-item-id="{{ item.id }}" data-ajax-url="{% url "EasyMove:add-comment" %}" data-user-name="{{ request.session.username }}" data-user-url="{% url "users:profile" request.session.username %}">Submit</button>
                    </div>
            </div>
            {% endif %}

        </div>


{% endblock %}

templates/EasyMove/easy_move/edit.html
{% extends "EasyMove/base.html" %}
{% load static %}
{% load humanize %}


{% block css-file %}
    <link rel="stylesheet" href="{% static "css/responsive-item.css" %}">
{% endblock %}


{% block content %}

    <div id="itemDetail">
            <div id="itemImageSet">
				<img src="{{ item.item_img.url}}" alt="image of {{item.title}}" />
			</div>

            <form id="editItem" action="{% url "EasyMove:submit-edit" item.id %}" method="POST">
            {#submit the editted item using POST method#}
                {% csrf_token %}

			    	<div id="info">
			    		<p class="price">Price: $<input type="number" id="add-price" name="add-price" min="0" value="{{ item.price }}" required/></p>
			    		<p class="name">Title: <input type="text" id="add-title" name="add-title" value="{{ item.title }}" required/></p>
			    		<p class="location">Location: <input type="text" id="add-location" name="add-location" value="{{ item.location }}" required/></p>
                        <p class="postedBy">Posted by: {{ item.author }}</p>
			    		<p class="avilability">Availability:
	    	                <input type="checkbox" id="checkDeliver" value="Deliver" name="add-availability">
	    	                <label for="checkDeliver">Deliver</label>
	    	                <input type="checkbox" id="checkPickup" value="Pickup" name="add-availability">
	    	                <label for="checkPickup">Pickup</label>
	    	                <input type="checkbox" id="checkMail" value="Mail" name="add-availability">
	    	                <label for="checkMail">Mail</label></p>
			    		<p class="postTime">Posted {{item.date_posted |naturaltime}}</p>
			    	</div>
			    	<hr/>
			    	<div id="condition">
			    		<h3>Condition: <input type="text" id="add-condition" name="add-condition" value="{{ item.condition }}" required/></h3>
			    		<p><textarea id="description" name="description" >{{ item.description }}</textarea></p>
			    	</div>
			    	<hr/>
                    <input type="submit" value="Submit Edit">
{#                    <button onclick="location.href = '{% url "EasyMove:item-detail" item.id %}' ">Cancel</button>#}
            </form>


    </div>



{% endblock %}

templates/EasyMove/easy_move/list.html
{% extends "EasyMove/base.html" %}
{% load static %}
{% block page-title %}Item list{% endblock %}


{% block css-file %}
    <link rel="stylesheet" href="{% static "css/responsive-home.css" %}">
{% endblock %}


{% block content %}

<div id="itemList">

    <div id="sortTools">
	    <div id="deliverOptions">
	    	<input type="checkbox" id="checkDeliver" name="deliver" checked>
	    	<label for="checkDeliver">Deliver</label>
	    	<input type="checkbox" id="checkPickup" name="pickup" checked>
	    	<label for="checkPickup">Pickup</label>
	    	<input type="checkbox" id="checkMail" name="mail" checked>
	    	<label for="checkMail">Mail</label>
	    </div>
	    <div id="sort">
	    	<select name="sortBy" id="sortBy" >
	    		<option value="newest">Newest</option>
{#	    		<option>Closet</option>#}
	    		<option value="priceH">Price:H</option>
	    		<option value="priceL">Price:L</option>
	    	</select>
		</div>
	</div>

    <div id="items">
        {% if items|length == 0 %}
            <h2>Sorry, there are no items right now.</h2>
        {% else %}
            {% for item in items %}
                {# iterate items and present in this page #}
                <a href="{% url "EasyMove:item-detail" item.id %}" class="itemBox" data-created-date="{{ item.date_posted }}">
    	            <img src="{{ item.item_img.url }}" alt="{{ item.title }}" />

    	            <p class="price" data-item-price="{{ item.price }}">${{ item.price }}</p>

    	            <p class="itemName">{{ item.title}}</p>
    	            <p class="location">{{ item.location}}</p>
    	    	    <p class="availability">{{ item.availability}}</p>
    	        </a>
            {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock %}

templates/EasyMove/easy_move/searchResult.html
{% extends "EasyMove/base.html" %}
{% load static %}
{% block page-title %}{% endblock %}

{% block css-file %}
    <link rel="stylesheet" href="{% static "css/search-result.css" %}">
{% endblock %}

{% block content %}

    {% if items|length == 0 %}
            <h2>Sorry, there are matched items.</h2>
        {% else %}
            {% for item in items %}
                {# iterate items and present in this page #}
                <div id="resultItems">
                    <a href="{% url "EasyMove:item-detail" item.id %}" class="itemBox" data-created-date="{{ item.date_posted }}">
    	                <img src="{{ item.item_img.url }}" alt="{{ item.title }}" />
                    
    	                <p class="price" data-item-price="{{ item.price }}">${{ item.price }}</p>
                    
    	                <p class="itemName">{{ item.title}}</p>
    	                <p class="location">{{ item.location}}</p>
    	    	        <p class="availability">{{ item.availability}}</p>
    	            </a>
                </div>

            {% endfor %}
        {% endif %}

{% endblock %}