EasyMove/urls.py
from django.urls import path
from . import views
app_name = 'EasyMove'
urlpatterns = [
    #item list view
    path('', views.home, name='easy-move-home'),
    path('item-list', views.easy_move_list, name = 'easy-move-list'),
    path('items/<int:item_id>', views.easy_move_items_detail, name="item-detail"),
    path('items/add-item', views.easy_move_add_item, name="add-item"),
    path('items/edit-item/<int:item_id>', views.easy_move_edit_item, name="edit-item"),
    path('items/edit-item/submit-edit/<int:item_id>',views.easy_move_submit_edit,name="submit-edit"),
    path('items/delete-item/<int:item_id>', views.easy_move_delete_item, name="delete-item"),
    path('change-location', views.easy_move_change_location, name="change-location"),
    path('items/<int:item_id>/compare', views.easy_move_item_compare, name="compare-item"),
    path('items/add-comment', views.new_comment_add,name="add-comment"),
    path('delete-comment', views.delete_comment, name="delete-comment"),
    path('edit-comment', views.edit_comment, name="edit-comment"),
    path('items/change-role', views.update_user_role, name="change-role"),
    path('search', views.item_search, name="item-search"),
]

cs5774DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('EasyMove/', include('EasyMove.urls', namespace='EasyMove')),
    path('users/', include('users.urls', namespace='users')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    #item list view
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name="profile"),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('edit-profile/<str:username>', views.edit_profile, name='edit-profile'),
    path('submit-profile-edit/<str:username>', views.submit_profile_edit, name='submit-profile-edit'),
    path('change-password', views.change_password, name='change-password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


# Create your models here.

class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="Regular", max_length=50)
    location = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('users:profile', args=[self.user.username])
 
@receiver(post_save, sender=User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.models import User
# from .models import User
from django.contrib import messages
from django.contrib.auth import authenticate
from django.http import JsonResponse
from actions.models import Action


# Create your views here.

def profile(request, username):
    user = get_object_or_404(User, username=username)

    actions = Action.objects.filter(user_id=user.id).order_by('-date_created')[:5]

    return render(request,
                  "users/user/profile.html",
                  {"user":user, "actions":actions}
                  )


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        duplicate_user = user = User.objects.filter(username=username)
        if len(duplicate_user) == 0:
            email = request.POST.get('email')
            password = request.POST.get('password')
            location = request.POST.get('location')
            user = User.objects.create_user(username, email, password)
            user.details.location=location
            user.save()

            # User should immediately logged in when successfully register
            request.session['username'] = user.username
            request.session['role'] = user.details.role
            request.session['location'] = user.details.location

            messages.add_message(request, messages.SUCCESS,
                             "You successfully registered with the username %s" % user.username)

            return redirect('EasyMove:easy-move-list')
        else:
             messages.add_message(request, messages.ERROR,
                                   "Username has been taken, try another")
    return render(request,
                  "users/user/register.html",
                  )

def login_user(request):
    username = request.POST.get("username")
    pw = request.POST.get("pw")
    user = authenticate(username=username, password=pw)
    if user is not None:
        request.session['username'] = user.username
        request.session['role'] = user.details.role
        request.session['location'] = user.details.location
        messages.add_message(request, messages.SUCCESS,
                             "You successfully logged in successfully")
        return redirect('EasyMove:easy-move-list')
    else:
        messages.add_message(request, messages.ERROR,
                             "Invalid username or password")
        return redirect('EasyMove:easy-move-home')


def logout_user(request):
    del request.session['username']
    del request.session['role']
    del request.session['location']
    return redirect('EasyMove:easy-move-home')



# link to edit profile page.
def edit_profile(request, username):
    user = User.objects.get(username=username)
    return render(request,
                  "users/user/editProfile.html",
                  {"user": user}
                  )


def submit_profile_edit(request, username):

    user = User.objects.get(username=username)

    if request.method == 'POST':
        # process the form

        firstname = request.POST.get("edit-firstname")
        lastname = request.POST.get("edit-lastname")
        email = request.POST.get("edit-email")
        location = request.POST.get("edit-location")

        # update information
        user.first_name = firstname
        user.last_name = lastname
        user.email = email
        user.details.location = location
        # save update
        user.save()

        messages.add_message(request, messages.INFO, "You successfully edited %s's profile" %user.username)

        return redirect("users:profile", user.username)
    else:
        # messages.add_message(request, messages.WARNING, "Failed edit the item %s" %editing_item.title)
        return redirect("users:edit-profile", user.username)


def change_password(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'

    if is_ajax and request.method == "POST":
        try:
            username = request.POST.get('username')
            user = User.objects.get(username=username)
            new_password = request.POST.get('new_password')
            user.set_password(new_password)
            user.save()
            return JsonResponse({'success': 'success'}, status=200)
        except User.DoesNotExist:
          #  if user not exist
            return JsonResponse({'error': 'No user found with that username'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request'}, status=400)

templates/users/user/editProfile.html
{% extends "EasyMove/base.html" %}
{% load static %}
{% block page-title %}Profile for {{ user.username }}{% endblock %}

{% block css-file %}
    <link rel="stylesheet" href="{% static "css/responsive-profile.css" %}">

{% endblock %}

{# This template is for the user's profile#}

{% block content %}
    <h2>Editing {{ user.username }}'s Profile</h2>

    <h3>User Detail</h3>


<div id="userProfile">
	<div id="userImage">
        <img src="{% static  "img/site/userImage.jpg" %}"  alt="image of user" />
	</div>


    <div id="detail-info" >

        <table>
            <form id="edit-profile-form" action="{% url "users:submit-profile-edit" user.username %}" method="POST">
                {% csrf_token %}
                <tr>
                    <td>Username: </td>
                    <td>{{ user.username }}</td>
                </tr>
                <tr>
                    <td>First Name: </td>
                    <td><input type="text" id="edit-firstname" name="edit-firstname"  value="{{ user.first_name }}"/></td>
                </tr>
                <tr>
                    <td>Last Name: </td>
                    <td><input type="text" id="edit-lastname" name="edit-lastname" value="{{ user.last_name }}"/></td>
                </tr>
                <tr>
                    <td>Email Address: </td>
                    <td><input type="email" id="edit-email" name="edit-email" value="{{ user.email }}" required/></td>
                </tr>
                <tr>
                    <td>Location: </td>
                    <td><input type="text" id="edit-location" name="edit-location" value="{{ user.details.location }}" required/></td>
                </tr>
                <tr>
                    <td>Role: </td>
                    <td id="user-role">{{ user.details.role }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Submit Update"></td>
                </tr>
            </form>
        </table>

    </div>

</div>

{% endblock %}

templates/users/user/profile.html
{% extends "EasyMove/base.html" %}
{% load static %}
{% load humanize %}
{% block page-title %}Profile for {{ user.username }}{% endblock %}

{% block css-file %}
    <link rel="stylesheet" href="{% static "css/responsive-profile.css" %}">

{% endblock %}

{# This template is for the user's profile#}

{% block content %}
    <h2>{{ user.username }}'s Profile</h2>

    <h3>User Detail</h3>


<div id="userProfile">
	<div id="userImage">
        <img src="{% static  "img/site/userImage.jpg" %}"  alt="image of user" />
	</div>


    <div id="detail-info" data-ajax-url="{% url "EasyMove:change-role" %}" data-user-name="{{ user.username }}">
        <table>
            <tr>
                <td>Username: </td>
                <td id="user-name">{{ user.username }}</td>
            </tr>
            <tr>
                <td>First Name: </td>
                <td id="user-first-name">{{ user.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name: </td>
                <td id="user-last-name">{{ user.last_name }}</td>
            </tr>
            <tr>
                <td>Email Address: </td>
                <td id="user-email">{{ user.email }}</td>
            </tr>
            <tr>
                <td>Location: </td>
                <td id="user-location">{{ user.details.location }}</td>
            </tr>
            <tr>
                <td>Role: </td>
                <td id="user-role">{{ user.details.role }}</td>
            </tr>
        </table>
    </div>

    <div id="editProfile">
        {% if request.session.role == "Admin" or request.session.username == user.username %}
            <button class="edit-user-profile" onclick="location.href='{% url "users:edit-profile" user.username %}' ">Edit</button>
            <button class="update-password" style="display: none" data-ajax-url="{% url "users:change-password" %}">Update Password</button>
            <button class="change-password">Change Password</button>
            {% if request.session.role == "Admin" %}
                <button id="change-role">Change Role</button>
            {% endif %}
        {% endif %}
    </div>

</div>


<div id="activities">
{% include "actions/action/feed.html" %}
</div>

{% endblock %}

templates/users/user/register.html
{% extends "EasyMove/base.html" %}
{% load static %}

{% block page-title %} | Register User{% endblock %}

{% block css-file %}
    <link rel="stylesheet" href="{% static "css/register.css" %}">
{% endblock %}

{% block content %}

<div id="register">
	{# This page will be directed to the list page after submitting the new item #}
	<form id="register-user" action="{% url 'users:register' %}" method="POST">
        <h2>Register your Account</h2>

        {% csrf_token %}
        <p>* = required.</p>

		<label for="register-username">Name*</label><br/>
		<input type="text" id="register-username" name="username" required/><br/>

        <label for="register-email">Email*</label><br/>
		<input type="email" id="register-email" name="email" required/><br/>

        <label for="register-location">Location*</label><br/>
		<input type="text" id="register-location" name="location" required/><br/>

        <label for="register-password">Password*</label><br/>
		<input type="password" id="register-password" name="password" required/><br/>


        <input type="submit" name="submit" value="Register"/><br/>

	</form>
</div>

{% endblock %}